spring.application.name=Student-Management-System

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3309/student_management_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Avocado2001}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
